// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VocalCoach.Modules.Progress.Infrastructure.Database;

#nullable disable

namespace VocalCoach.Modules.Progress.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ProgressDbContext))]
    [Migration("20261006050139_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("progress")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VocalCoach.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_occurred_on_utc")
                        .HasFilter("processed_on_utc IS NULL");

                    b.ToTable("outbox_messages", "progress");
                });

            modelBuilder.Entity("VocalCoach.Modules.Progress.Domain.ItemBest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ItemId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("BestScore")
                        .HasColumnType("integer")
                        .HasColumnName("best_score");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTime>("LastAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_at_utc");

                    b.Property<int>("LastScore")
                        .HasColumnType("integer")
                        .HasColumnName("last_score");

                    b.Property<bool>("PassedEver")
                        .HasColumnType("boolean")
                        .HasColumnName("passed_ever");

                    b.HasKey("UserId", "ItemId")
                        .HasName("pk_item_bests");

                    b.ToTable("item_bests", "progress");
                });

            modelBuilder.Entity("VocalCoach.Modules.Progress.Domain.LearnerProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("Passed")
                        .HasColumnType("integer")
                        .HasColumnName("passed");

                    b.Property<double>("TotalSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("total_seconds");

                    b.HasKey("Id")
                        .HasName("pk_learner_progress");

                    b.ToTable("learner_progress", "progress");
                });

            modelBuilder.Entity("VocalCoach.Modules.Progress.Domain.PracticeDay", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.HasKey("UserId", "Day")
                        .HasName("pk_practice_days");

                    b.ToTable("practice_days", "progress");
                });

            modelBuilder.Entity("VocalCoach.Modules.Progress.Infrastructure.Database.ProcessedAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("AttemptId")
                        .HasName("pk_processed_attempts");

                    b.ToTable("processed_attempts", "progress");
                });

            modelBuilder.Entity("VocalCoach.Modules.Progress.Domain.ItemBest", b =>
                {
                    b.HasOne("VocalCoach.Modules.Progress.Domain.LearnerProgress", null)
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_bests_learner_progress_user_id");
                });

            modelBuilder.Entity("VocalCoach.Modules.Progress.Domain.PracticeDay", b =>
                {
                    b.HasOne("VocalCoach.Modules.Progress.Domain.LearnerProgress", null)
                        .WithMany("Days")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practice_days_learner_progress_user_id");
                });

            modelBuilder.Entity("VocalCoach.Modules.Progress.Domain.LearnerProgress", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
