<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../VocalCoach.Modules.Practice.Application/VocalCoach.Modules.Practice.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/VocalCoach.BuildingBlocks.Presentation/VocalCoach.BuildingBlocks.Presentation.csproj" />
  </ItemGroup>
</Project>
