<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
    <ProjectReference Include="../VocalCoach.BuildingBlocks.Application/VocalCoach.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
